// Generated by gencpp from file glass_ladder/ladderRequest.msg
// DO NOT EDIT!


#ifndef GLASS_LADDER_MESSAGE_LADDERREQUEST_H
#define GLASS_LADDER_MESSAGE_LADDERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace glass_ladder
{
template <class ContainerAllocator>
struct ladderRequest_
{
  typedef ladderRequest_<ContainerAllocator> Type;

  ladderRequest_()
    : step()  {
    }
  ladderRequest_(const ContainerAllocator& _alloc)
    : step(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _step_type;
  _step_type step;





  typedef boost::shared_ptr< ::glass_ladder::ladderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::glass_ladder::ladderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ladderRequest_

typedef ::glass_ladder::ladderRequest_<std::allocator<void> > ladderRequest;

typedef boost::shared_ptr< ::glass_ladder::ladderRequest > ladderRequestPtr;
typedef boost::shared_ptr< ::glass_ladder::ladderRequest const> ladderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::glass_ladder::ladderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::glass_ladder::ladderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::glass_ladder::ladderRequest_<ContainerAllocator1> & lhs, const ::glass_ladder::ladderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.step == rhs.step;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::glass_ladder::ladderRequest_<ContainerAllocator1> & lhs, const ::glass_ladder::ladderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace glass_ladder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::glass_ladder::ladderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::glass_ladder::ladderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glass_ladder::ladderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glass_ladder::ladderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glass_ladder::ladderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glass_ladder::ladderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::glass_ladder::ladderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2ee9423a5e4755eeacf5800eb738c64";
  }

  static const char* value(const ::glass_ladder::ladderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2ee9423a5e4755eULL;
  static const uint64_t static_value2 = 0xeacf5800eb738c64ULL;
};

template<class ContainerAllocator>
struct DataType< ::glass_ladder::ladderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "glass_ladder/ladderRequest";
  }

  static const char* value(const ::glass_ladder::ladderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::glass_ladder::ladderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string step\n"
;
  }

  static const char* value(const ::glass_ladder::ladderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::glass_ladder::ladderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ladderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::glass_ladder::ladderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::glass_ladder::ladderRequest_<ContainerAllocator>& v)
  {
    s << indent << "step: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLASS_LADDER_MESSAGE_LADDERREQUEST_H
