// Generated by gencpp from file glass_ladder/Ladder.msg
// DO NOT EDIT!


#ifndef GLASS_LADDER_MESSAGE_LADDER_H
#define GLASS_LADDER_MESSAGE_LADDER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace glass_ladder
{
template <class ContainerAllocator>
struct Ladder_
{
  typedef Ladder_<ContainerAllocator> Type;

  Ladder_()
    : msg()  {
    }
  Ladder_(const ContainerAllocator& _alloc)
    : msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::glass_ladder::Ladder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::glass_ladder::Ladder_<ContainerAllocator> const> ConstPtr;

}; // struct Ladder_

typedef ::glass_ladder::Ladder_<std::allocator<void> > Ladder;

typedef boost::shared_ptr< ::glass_ladder::Ladder > LadderPtr;
typedef boost::shared_ptr< ::glass_ladder::Ladder const> LadderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::glass_ladder::Ladder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::glass_ladder::Ladder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::glass_ladder::Ladder_<ContainerAllocator1> & lhs, const ::glass_ladder::Ladder_<ContainerAllocator2> & rhs)
{
  return lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::glass_ladder::Ladder_<ContainerAllocator1> & lhs, const ::glass_ladder::Ladder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace glass_ladder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::glass_ladder::Ladder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::glass_ladder::Ladder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glass_ladder::Ladder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glass_ladder::Ladder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glass_ladder::Ladder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glass_ladder::Ladder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::glass_ladder::Ladder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const ::glass_ladder::Ladder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d96ed7307768047ULL;
  static const uint64_t static_value2 = 0x54140b85e64c862eULL;
};

template<class ContainerAllocator>
struct DataType< ::glass_ladder::Ladder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "glass_ladder/Ladder";
  }

  static const char* value(const ::glass_ladder::Ladder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::glass_ladder::Ladder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg\n"
;
  }

  static const char* value(const ::glass_ladder::Ladder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::glass_ladder::Ladder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ladder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::glass_ladder::Ladder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::glass_ladder::Ladder_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLASS_LADDER_MESSAGE_LADDER_H
